import { TPricingData } from "./type";

export const pricingData: TPricingData[] = [
  {
    id: 1,
    name: "Basic",
    priceSymbol: "$",
    price: 650,
    pricePrefix: "",
    pricePostfix: "/per hour",
    priceDescription:
      "Ideal for individuals and small businesses entering the online space",
    featureTitle: "Why should you take this",
    features: [
      "Standard website development using pre-designed templates",
      "Basic customization options for branding",
      "Limited SEO optimization for essential visibility.",
      "Email support for technical assistance",
      "Domain registration guidance",
    ],
    buttonTitle: "Start Your Project",
    buttonUrl: "#",
    isPopular: false,
  },
  {
    id: 2,
    name: "Standard",
    priceSymbol: "$",
    price: 950,
    pricePrefix: "",
    pricePostfix: "/per hour",
    priceDescription: "Suitable for growing businesses with moderate needs.",
    featureTitle: "Why should you take this",
    features: [
      "Custom website development with access to premium templates",
      "Extensive customization for branding and user experience",
      "Basic on-page SEO optimization for improved search rankings",
      "Domain registration, management, and DNS configuration",
      "Integration with essential third-party tools and plugins",
      "Email and phone support for technical queries",
    ],
    buttonTitle: "Start Your Project",
    buttonUrl: "#",
    isPopular: true,
    popularText: "Save 30 %",
  },
  {
    id: 3,
    name: "Premium",
    priceSymbol: "$",
    price: 1350,
    pricePrefix: "",
    pricePostfix: "/per hour",
    priceDescription:
      "Tailored for businesses requiring advanced features and support",
    featureTitle: "Why should you take this",
    features: [
      "Fully customized website development tailored to your brand identity",
      "Advanced user experience design for enhanced engagement",
      "Comprehensive SEO optimization including on-page, off-page, and technical aspects",
      "24/7 priority support via email, phone, and live chat",
      "Domain registration, management, and renewal with dedicated support",
      "Integration with advanced third-party services for enhanced functionality",
      "Performance optimization for faster loading times and better user experience",
    ],
    buttonTitle: "Start Your Project",
    buttonUrl: "#",
    isPopular: false,
  },
];
